### ISSUE TITLE
Self-Signed Certificate is NOT verified while connecting to processing server

### ISSUE THREAD

**Issue by ghost** [plugandpay/tbc-credit-card-payment-gateway-php-lib#2]
**მიმდინარე მდგომარეობა:**
პროცესინგის სერვერთან დაკავშირებისას, სადაც გამოყენებულია Self-Signed სერტიფიკატი, არ ხდება ამ უკანასკნელი სერტიფიკატის შემოწმება. რადგან არსებული Self-Signed სერტიფიკატი იწვევს კავშირის შეფერხებას ნორმალურ პირობებში(Default კონფიგურაციით), ამიტომ აქ გამოყენებულია ალტერნატიული გზა და SSL სერტიფიკატის შემოწმება საერთოდ არ ხდება ზემოთ აღნიშნული შეფერხების თავიდან აცილების მიზნით [იხ. შემდეგი ფრაგმენტი](https://github.com/wearede/tbcpay-php/blob/d4445bfae71c52da0b01b31f751479a686b3feaf/tbcpay.lib.php#L119-L120):

``` php
            curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
```

**სასურველი მდგომარეობა:**
შემოწმდეს Self-Signed სერტიფიკატი, ბანკისგან ან სარწმუნო წყაროსგან მიღებული root სერტიფიკატის დახმარებით.

**Comment by ghost** [comment]
root სერტიფიკატთან დაკავშირებით Support-ის შეტყობინება:

> „Pkcs keystor -ში რომელიც გამოგზავნილია თქვენთვის არის  root სერტიფიკატი, რომლითაც შეგიძლიათ დაამატოთ self signed სერტიფიკატები. სურვილის შემთხვევაში შეგვიძლია root სერტიფიკატი მოგაწოდოთ ცალკე.“

**Comment by sandrodz** [comment]
awesome, accepting PR :+1:

**Comment by ghost** [comment]
ბანკის მიერ მოწოდებული PKCS12 Keystore-დან root სერტიფიკატის მიღება (იმ შემთხვევისთვის, თუ გჭირდებათ ეს root სერტიფიკატი გქონდეთ ცალკე):

``` bash
openssl pkcs12 -in *.p12 -out tbcpay.ca.pem  -cacerts -nokeys
```

თუ ასე ვერ მიიღებთ, მოითხოვეთ და ცალკე მოგაწოდებენ...

**Comment by sandrodz** [comment]
რა შემთხვევაში იქნება ეს შემოწმება საჭირო?

სერვერი ხომ ჩვენს ხელში ანუ აპლიკაციის ავტორის ხელში, დნს -ი მითითებულია google-ის ვთქვათ, რექვესტი ჩვენგან გადის ბანკის url-ზე... ამ შემთხვევაში ხომ ისედაც ვიცით რომ ბანკს მისდის ეს რექვესტი?

isn't this redundant?

**Comment by ghost** [comment]
მე მქონდა ინტეგრაციის პროცესში პრობლემა იმის გამო, რომ არ მივაქციე ყურადღება იმას, რომ Self-Signed სერტიფიკატი იყო გამოყენებული და Default კონფიგურაციით ვცდილობდი დაკავშირებას... ცხადია ვერ დავუკავშირდი სერვერს... ეს იყო ძირითადი პრობლემა. როცა გავარკვიე, რომ Self-Signed სერტიფიკატთან მქონდა საქმე, ვნახე 2 შესაძლო სოლუშენი:
1. საერთოდ არ ვიყენებთ (გავთიშავთ) SSL სერტიფიკატის შემოწმებას, როგორც ეს თქვენს შემთხვევაში არის გაკეთებული.
2. ვამოწმებთ SSL სერტიფიკატს root სერტიფიკატის დახმარებით.
   
   აქედან რეკომენდებული გზა არის მეორე. 
   
   UPDATE:
   მე აქ გამომრჩა მესამე ოფცია, რადგან იმ ზომებზე ვფიქრობდი რაც ჩვენ შეგვიძლია მივიღოთ დამოუკიდებლად, თუმცა არის ასეთი ვარიანტიც:
3. ბანკი ცვლის Self-Signed სერტიფიკატს ნორმალური Trusted სერტიფიკატით.

მესამე შემთხვევაში საკმარისი იქნებოდა უბრალოდ ზევით აღნიშნული ორი ხაზის წაშლა კოდიდან (იმისთვის რომ ისევ გააქტიურდეს გამორთული SSL სერტიფიკატის შემოწმება) და შეუფერხებელი კავშირიც გვექნებოდა SSL სერტიფიკატის Default კონფიგურაციით შემოწმებასთან ერთად. მაგრამ როგორც ჩანს ეს Self-Signed სერტიფიკატი კიდევ დიდხანს იქნება უცვლელად გამოყენებული Production Environment-ში ბანკის მხრიდან (თავიდანვე უნდა გაეშვათ Trusted სერტიფიკატით... რადგან ახლა შეცვლამ შეიძლება სხვა პრობლემები გამოიწვიოს, კერძოდ მერჩანტებს, ვისაც ადაპტირებული აქვს კოდი Self-Signed სერტიფიკატზე, დაჭირდებათ ცვლილება მუშაობის გასაგრძელებლად...), შეიძლება როდისმე შეცვალონ კიდეც (საინტერესოა საერთოდ რატომ იყენებს ბანკი ასეთი დონის სერვისში Self-Signed და არა Trusted სერტიფიკატს?! ), მაგრამ მანამდე საუკეთესო ვარიანტად რჩება მეორე.

**Comment by ghost** [comment]
შეილება რექვესტი მიდის ბანკში, მაგრამ გზაში მესამე მხარე განშიფრავს ინფორმაციას, ნახულობს, თუ მოუნდება შეცვლის, მერე ისევ დაშიფრავს და სხვა Self-Signed სერტიფიკატით "ადასტურებს". თუ არ მოწმდება, რომ ეს ნამდვილად "ის" სერტიფიკატია, რომლითაც ბანკის სერვერზე მოხდა დაშიფრვა (მაგას ამოწმებ ისევ ბანკიდან მიღებული root სერტიფიკატით) მაშინ შეილება გზაში ხედავენ ინფორმაციას. მოკლედ სტანდარტული MIM. შეილება სადღაც ჩინეთში ვიშოვე სერვერი (ან VPS) და ბევრი როუტერი უნდა გაიაროს ჩემმა რექვესტმა.. ან ადმინი არ ვარ და google-ს დნს ვერ ჩავუწერ... 
რათქმაუნდა, მარტო ამ სერტიფიკატზე დამოკიდებული არ ვართ, + კლიენტის სერტიფიკატი ფიგურირებს და სხვა დამატებითი ზომები არის მიღებული ბანკის მხრიდან და MIM ასე მარტივად არ მოხდება, როგორც ზევით დავწერე. მაგრამ პოტენციურად MIM-ს ხელს უწყობს სერტიფიკატის შემოწმების გათიშვა. ამიტომ, იყოს რეკომენდებული სოლუშენი, რახან არჩევანი გვაქვს.

**Comment by sandrodz** [comment]
ოკ, you convinced me :) ჩავიხედები გავტესტავ და დავააფდეითებ.
